# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

strategy:
  matrix:
    node10:
      nodeVersion: '10.x'
    node12:
      nodeVersion: '12.x'
      executeSonar: true
    node14:
      nodeVersion: '14.x'

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'silamoney'
    scannerMode: 'CLI'
    configMode: 'file'
  displayName: 'Prepare Sonar analysis'
  condition: and(succeeded(), eq(variables['executeSonar'], true))

- task: NodeTool@0
  inputs:
    versionSpec: '$(nodeVersion)'
  displayName: 'Install Node.js $(nodeVersion)'

- script: npm install
  displayName: 'npm install $(nodeVersion)'

- script: npm test
  displayName: 'npm test $(nodeVersion)'
  env:
    SILA_PRIVATE_KEY: $(silaPrivateKey)

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'coverage/test-*.xml'
  displayName: 'Publish test results'
  condition: succeededOrFailed()

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: 'coverage/cobertura-coverage.xml'

- task: SonarCloudAnalyze@1
  condition: and(succeededOrFailed(), eq(variables['executeSonar'], true))

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
  condition: and(succeeded(), eq(variables['executeSonar'], true))
